### ISSUE TITLE
Good Project Team! I Like it.

### ISSUE THREAD

**Issue by rahXephonz** [fate-awaken/ied-cake#4]
Just give appreciate, not an real issues :)

**Comment by rahXephonz** [comment]
is this project using php?

**Comment by solahkay** [comment]
> 

Nope. Just HTML. CSS, and Javascript. Just a normal project for Web Programming discipline.

**Comment by rahXephonz** [comment]
> > 
> 
> Nope. Just HTML. CSS, and Javascript. Just a normal project for Web Programming discipline.

nice!

**Comment by diasujamuru** [comment]
> Just give appreciate, not an real issues :)

Thank you!

**Comment by rahXephonz** [comment]
Ok Semangat everyone ;)
